#!/usr/bin/env python3
"""浏览器 cookies → Netscape cookies.txt 转换器。

支持两种输入格式（自动检测）：
1. Playwright storage_state JSON：{"cookies": [ {name,value,domain,path,expires,httpOnly,secure,sameSite}, ... ]}
   （browser-harness 的 cdp("Network.getAllCookies") 返回的 cookie 也是这个结构）
2. 纯 cookie 数组：[ {name,value,domain,path,expires,httpOnly,secure}, ... ]

yt-dlp / gallery-dl 需要 Netscape 格式的 cookies.txt，本脚本做转换。

用法：
  python3 storage_state_to_netscape.py /tmp/state.json -o cookies/vimeo.txt [--domain vimeo.com]
  python3 storage_state_to_netscape.py /tmp/state.json -o out.txt   # 全部 cookie

--domain 只导出匹配该域的 cookie（推荐：每平台一个文件，如 youtube.txt/vimeo.txt）。
"""
import argparse
import json
import sys
from datetime import datetime, timezone

NETSCAPE_HEADER = """# Netscape HTTP Cookie File
# Generated by media-downloader (browser cookies -> cookies.txt)
# https://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file! Do not edit.
"""


def convert(state_path: str, domain_filter: str | None) -> list[str]:
    with open(state_path, encoding="utf-8") as f:
        state = json.load(f)

    # 自动检测格式：{"cookies": [...]} 或纯数组
    if isinstance(state, dict) and isinstance(state.get("cookies"), list):
        cookies = state["cookies"]
    elif isinstance(state, list):
        cookies = state
    else:
        print("ERROR: 无法识别的 cookies 格式（需 {\"cookies\":[...]} 或 [...]）", file=sys.stderr)
        sys.exit(1)

    lines = []
    for c in cookies:
        host = c.get("domain", "")
        if domain_filter and domain_filter not in host:
            continue
        name = c.get("name", "")
        value = c.get("value", "")
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        # domain 以 . 开头即 domain cookie，否则 host-only
        domain_specified = "TRUE" if host.startswith(".") else "FALSE"
        # 过期时间：Playwright 默认 -1（session）；CDP session cookie 的 expires 为 -1 或缺失
        expires = c.get("expires", -1)
        if isinstance(expires, (int, float)):
            expires = int(expires)
        else:
            expires = 0
        lines.append(f"{host}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

    return lines


def main() -> int:
    ap = argparse.ArgumentParser(description="浏览器 cookies → Netscape cookies.txt")
    ap.add_argument("state", help="cookies JSON 文件路径（Playwright storage_state 或 CDP cookies 数组）")
    ap.add_argument("-o", "--output", required=True, help="输出 cookies.txt 路径")
    ap.add_argument("--domain", help="只导出匹配该域的 cookie")
    args = ap.parse_args()

    lines = convert(args.state, args.domain)

    header = [NETSCAPE_HEADER.rstrip("\n"), f"# Exported: {datetime.now(timezone.utc).isoformat()}",
              f"# Cookies: {len(lines)}"]
    if args.domain:
        header.append(f"# Domain filter: {args.domain}")
    header.append("")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(header))
        f.write("\n")
        for line in lines:
            f.write(line + "\n")

    print(f"OK: {len(lines)} cookies -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())